all_files_and_dir:
	ls -la
.phony: run_image

run_image:
	docker run -p 5000:80 --rm \
	--name $(MODULE_NAME) \
	--env-file=./config.env $(ACCOUNT_NAME)/$(MODULE_NAME):$(VERSION_TAG)
.phony: run_image