export default {
  red: (message: string) => console.log('\x1b[31m%s\x1b[0m', message),
  green: (message: string) => console.log('\x1b[32m%s\x1b[0m', message),
  yellow: (message: string) => console.log('\x1b[33m%s\x1b[0m', message),
  blue: (message: string) => console.log('\x1b[34m%s\x1b[0m', message),
  magenta: (message: string) => console.log('\x1b[35m%s\x1b[0m', message),
  cyan: (message: string) => console.log('\x1b[36m%s\x1b[0m', message),
  white: (message: string) => console.log('\x1b[37m%s\x1b[0m', message),
  gray: (message: string) => console.log('\x1b[90m%s\x1b[0m', message),
  black: (message: string) => console.log('\x1b[90m%s\x1b[0m', message),
  bgRed: (message: string) => console.log('\x1b[41m%s\x1b[0m', message),
  bgGreen: (message: string) => console.log('\x1b[42m%s\x1b[0m', message),
  bgYellow: (message: string) => console.log('\x1b[43m%s\x1b[0m', message),
  bgBlue: (message: string) => console.log('\x1b[44m%s\x1b[0m', message),
  bgMagenta: (message: string) => console.log('\x1b[45m%s\x1b[0m', message),
  bgCyan: (message: string) => console.log('\x1b[46m%s\x1b[0m', message),
  bgWhite: (message: string) => console.log('\x1b[47m%s\x1b[0m', message),
  bgGray: (message: string) => console.log('\x1b[100m%s\x1b[0m', message),
  bgBlack: (message: string) => console.log('\x1b[100m%s\x1b[0m', message),
}
